import {
	DEFAULT_BATCHED_SESSION_ROUTER_MODULE,
	DEFAULT_SESSION_KEY_MANAGER_MODULE,
	DEFAULT_ERC20_MODULE
} from "@biconomy/account";

export const erc20ModuleAddr = DEFAULT_ERC20_MODULE;
export const managerModuleAddr = DEFAULT_SESSION_KEY_MANAGER_MODULE;
export const routerModuleAddr = DEFAULT_BATCHED_SESSION_ROUTER_MODULE;
